### ISSUE TITLE
plugin version shows other plugin name

### ISSUE THREAD

**Issue by senlin** [phpbits/easy-login-styler#1]
See here: https://github.com/phpbits/easy-login-styler/blob/master/plugin.php#L71

might need to release 1.0.1 :)

**Comment by phpbits** [comment]
[Fix](https://github.com/phpbits/easy-login-styler/commit/b5917c01ef15544c1eaf93fe0c0eb6c221bd1941) added ;) Closing this issue now. Thanks!
